### ISSUE TITLE
Correction

### ISSUE THREAD

**Issue by thubalek** [Flying-Toast/qiyi_smartcube_protocol#1]
I believe there is an error/inconsistency in the documentation. 

At https://github.com/Flying-Toast/qiyi_smartcube_protocol?tab=readme-ov-file#message-acknowledgement it says that the ACK contains bytes 3-7 of the original message. 

I'm a bit confused by this, because there should be bytes from position 2 (if the field starts with 0). 

In the rest of the documentation it looks like indexes starting from 0 are used.

Anyway: thank you very much for the documentation of this protocol. You did an amazing job, it's a pleasure to work with such high quality documentation. Thanks again.

**Comment by Flying-Toast** [comment]
That was intentional, since it's referring to "bytes X, Y, Z..." rather than "the range of N bytes starting at index X". But do you think it would be more clear if written in another way?
